'use strict';
// Английский словарь. Ключ — русская строка из кода (по одной строке экрана: тексты
// с \n переводятся построчно), значение — перевод. Составные строки с числами и
// именами разбирают шаблоны EN_PATTERNS и разделители в js/i18n.js.

const EN = {
  // --- меню ---
  'Лёгкий': 'Easy', 'Нормальный': 'Normal', 'Сложный': 'Hard', 'Кошмар': 'Nightmare',
  'Продолжить': 'Continue',
  'Начать уровень заново': 'Restart level',
  'Настройки': 'Settings',
  'Управление': 'Controls',
  'Главное меню': 'Main menu',
  'Звуки': 'Sound',
  'Музыка': 'Music',
  'Яркость': 'Brightness',
  'Тряска экрана': 'Screen shake',
  'вкл': 'on', 'выкл': 'off',
  'Передний план': 'Foreground',
  'Язык': 'Language',
  'Клавиши': 'Keys',
  'Во весь экран': 'Fullscreen',
  'Назад': 'Back',
  'Эпизод': 'Episode',
  '(секрет)': '(secret)',
  'Лучшее время': 'Best time',
  'Рекорд': 'Record',
  'убито': 'kills',
  'тайники': 'secrets',
  'Сбросить по умолчанию': 'Reset to defaults',
  'Клавиши сброшены': 'Keys reset',
  'Настроить клавиши': 'Configure keys',
  'Новая игра': 'New game',
  'Выбор уровня': 'Select level',
  'Отменено': 'Cancelled',
  'ПАУЗА': 'PAUSED',
  'двумерный шутер в духе Quake': 'a 2D shooter in the spirit of Quake',
  'Slipgate — двумерный шутер в духе Quake': 'Slipgate — a 2D shooter in the spirit of Quake',
  'НАСТРОЙКИ': 'SETTINGS',
  'КЛАВИШИ': 'KEYS',
  'НОВАЯ ИГРА': 'NEW GAME',
  'ВЫБОР УРОВНЯ': 'SELECT LEVEL',
  'СЛОЖНОСТЬ': 'DIFFICULTY',
  'УПРАВЛЕНИЕ': 'CONTROLS',
  'Enter — назначить клавишу. Цифры 1–8, Esc и P заняты.': 'Enter — assign a key. Digits 1–8, Esc and P are reserved.',
  'Фанатская игра. Все звуки и графика созданы кодом.': 'A fan game. All sound and graphics are made by code.',
  // экран «Управление»
  'бег': 'move',
  'прыжок, всплытие': 'jump, swim up',
  'сквозь платформу, нырок': 'drop through, dive',
  'Мышь': 'Mouse',
  'прицел': 'aim',
  'ЛКМ': 'LMB',
  'огонь': 'fire',
  'колесо': 'wheel',
  'оружие': 'weapons',
  'карта: пока держите / закрепить': 'map: hold / pin',
  'пауза': 'pause',
  'музыка': 'music',
  'Геймпад': 'Gamepad',
  'левый стик — бег, правый — прицел': 'left stick — move, right — aim',
  'A — прыжок, RT — огонь, LB / RB — оружие': 'A — jump, RT — fire, LB / RB — weapons',
  'Сенсорный экран': 'Touchscreen',
  'слева стик, справа прицел и огонь': 'stick on the left, aim and fire on the right',
  'Совет': 'Tip',
  'ракета под ноги = высокий прыжок': 'rocket at your feet = high jump',
  'стреляйте в подозрительные стены': 'shoot suspicious-looking walls',

  // --- клавиши ---
  'Влево': 'Left',
  'Вправо': 'Right',
  'Прыжок, всплытие': 'Jump, swim up',
  'Вниз, нырок': 'Down, dive',
  'Огонь (и левая кнопка мыши)': 'Fire (and left mouse button)',
  'Следующее оружие': 'Next weapon',
  'Предыдущее оружие': 'Previous weapon',
  'Карта (пока держите)': 'Map (while held)',
  'Карта вкл/выкл': 'Map on/off',
  'Музыка вкл/выкл': 'Music on/off',
  'Пробел': 'Space',
  'Правый Ctrl': 'Right Ctrl',
  'Правый Shift': 'Right Shift',
  'Правый Alt': 'Right Alt',

  // --- приложение ---
  'SLIPGATE установлен — значок на главном экране': 'SLIPGATE installed — icon on your home screen',
  'В Safari: кнопка «Поделиться» (квадрат со стрелкой)': 'In Safari: tap “Share” (square with an arrow)',
  '→ «На экран „Домой“» → «Добавить»': '→ “Add to Home Screen” → “Add”',
  'Обновить игру': 'Update game',
  'новая версия уже скачана': 'a new version is downloaded',
  'Установить на телефон': 'Install on phone',
  'значок на главном экране, игра без интернета': 'home screen icon, plays offline',

  // --- оружие и патроны ---
  'Топор': 'Axe',
  'Ружьё': 'Shotgun',
  'Двустволка': 'Super Shotgun',
  'Гвоздомёт': 'Nailgun',
  'Супергвоздомёт': 'Super Nailgun',
  'Гранатомёт': 'Grenade Launcher',
  'Ракетница': 'Rocket Launcher',
  'Громовержец': 'Thunderbolt',
  'Лазерная пушка': 'Laser Cannon',
  'патроны': 'shells',
  'гвозди': 'nails',
  'ракеты': 'rockets',
  'батареи': 'cells',

  // --- монстры ---
  'Солдат': 'Grunt', 'Пёс': 'Rottweiler', 'Каратель': 'Enforcer', 'Рыцарь': 'Knight', 'Огр': 'Ogre',
  'Зомби': 'Zombie', 'Изверг': 'Fiend', 'Скраг': 'Scrag', 'Рыцарь Смерти': 'Death Knight', 'Ворог': 'Vore',
  'Порождение': 'Spawn', 'Шамблер': 'Shambler', 'Гаргулья': 'Gargoyle', 'Шуб-Ниггурат': 'Shub-Niggurath',
  'Скорпион': 'Scorpion', 'Угорь': 'Eel', 'Кристалл': 'Crystal', 'Вестник Бездны': 'Herald of the Abyss',
  'Фантом': 'Phantom', 'Страж': 'Guardian', 'Древний': 'The Elder', 'Хтон': 'Chthon',

  // --- боссы: таблички и полоска ---
  'ХТОН': 'CHTHON', 'Владыка Лавы': 'Lord of Lava',
  'ШУБ-НИГГУРАТ': 'SHUB-NIGGURATH', 'Мать Тысячи Отродий': 'Mother of a Thousand Spawn',
  'ВЕСТНИК БЕЗДНЫ': 'HERALD OF THE ABYSS', 'Глас Нижнего мира': 'Voice of the Netherworld',
  'ДРЕВНИЙ': 'THE ELDER', 'Пожиратель Измерений': 'Devourer of Dimensions',
  'повержен': 'defeated',
  'барьер, руны': 'barrier, runes',
  'ОГЛУШЁН — БЕЙТЕ!': 'STUNNED — HIT HIM!',
  'ЯРОСТЬ': 'RAGE',
  'щит, кристаллов': 'shield, crystals',
  'ГРОЗА БЕЗДНЫ': 'ABYSS STORM',
  'ЛАВА ПОДНИМАЕТСЯ!': 'LAVA RISING!',
  'электроды': 'electrodes',
  'ТЕЛЕПОРТ ОТКРЫТ — ВНУТРЬ!': 'TELEPORTER OPEN — GET IN!',
  'кровь для телепорта': 'blood for the teleporter',

  // --- строка состояния и сенсорное управление ---
  'ТОПОР': 'AXE',
  'ВОЗДУХ': 'AIR',
  'бег · вверх — прыжок': 'move · up — jump',
  'прицел и огонь': 'aim and fire',

  // --- гибель ---
  'Вас застрелил солдат': 'A grunt shot you',
  'Вас загрыз пёс': 'A rottweiler mauled you',
  'Вас поджарил каратель': 'An enforcer fried you',
  'Вас зарубил рыцарь': 'A knight cut you down',
  'Вас сжёг рыцарь смерти': 'A death knight burned you',
  'Вас распилил огр': 'An ogre chainsawed you',
  'Вас закидал плотью зомби': 'A zombie pelted you with flesh',
  'Вас растерзал изверг': 'A fiend tore you apart',
  'Вас оплевал скраг': 'A scrag spat on you',
  'Вас уничтожил ворог': 'A vore destroyed you',
  'Вас сожрало порождение': 'A spawn devoured you',
  'Вас испепелил шамблер': 'A shambler fried you',
  'Вас испепелил Хтон': 'Chthon incinerated you',
  'Вас растерзала гаргулья': 'A gargoyle tore you apart',
  'Вас поглотила Шуб-Ниггурат': 'Shub-Niggurath consumed you',
  'Вас изрешетил скорпион': 'A scorpion riddled you',
  'Вас ударил током угорь': 'An eel electrocuted you',
  'Вас испепелил Вестник Бездны': 'The Herald incinerated you',
  'Вас настиг фантом': 'A phantom caught you',
  'Вас сокрушил страж': 'A guardian crushed you',
  'Вас стёр из бытия Древний': 'The Elder unmade you',
  'Вы погибли': 'You died',
  'Вы разрядили молнию в воде': 'You discharged in the water',
  'Вы подорвали себя': 'You blew yourself up',
  'Вы сгорели в лаве': 'You burned in the lava',
  'Вы растворились в слизи': 'You dissolved in slime',
  'Вы утонули': 'You drowned',
  'Вы разбились': 'You fell to your death',
  'Вас разорвало взрывом': 'An explosion tore you apart',
  'Вас расплющило давилкой': 'A crusher flattened you',
  'Вас поглотила пустота': 'The void swallowed you',
  'Нажмите огонь, чтобы вернуться к контрольной точке': 'Press fire to return to the checkpoint',
  'Нажмите огонь, чтобы начать заново': 'Press fire to start over',
  'Коснитесь экрана, чтобы вернуться к контрольной точке': 'Tap the screen to return to the checkpoint',
  'Коснитесь экрана, чтобы начать заново': 'Tap the screen to start over',

  // --- финалы эпизодов ---
  'Туша Хтона погружается обратно в лаву,': 'Chthon’s carcass sinks back into the lava',
  'из которой он поднялся. Земля затихает.': 'he rose from. The earth falls silent.',
  'На остывающем камне лежит древняя руна.': 'On the cooling stone lies an ancient rune.',
  'Вы сжимаете её — и чувствуете, как': 'You grip it — and feel a strange,',
  'по жилам течёт чужая, первобытная сила.': 'primeval power flow through your veins.',
  'Руна раскрывает новый слипгейт. За ним —': 'The rune opens a new slipgate. Beyond it',
  'Царство Чёрной Магии, где ждёт та,': 'lies the Realm of Black Magic and the one',
  'что породила Хтона.': 'who gave birth to Chthon.',
  'Эпизод 1 пройден. Впереди — Эпизод 2.': 'Episode 1 complete. Next: Episode 2.',
  'Телепорт вышвыривает вас прямо в её чрево,': 'The teleporter hurls you into her womb,',
  'и Шуб-Ниггурат рвётся изнутри, как гнилой плод.': 'and Shub-Niggurath bursts like rotten fruit.',
  'Щупальца опадают. Глаза гаснут один за другим.': 'Tentacles go limp. Her eyes die one by one.',
  'Вторая руна тёплая, как живое сердце.': 'The second rune is warm as a living heart.',
  'Но руна раскрывает путь ещё глубже —': 'But it opens a path deeper still —',
  'в Нижний мир, откуда приходят все кошмары.': 'to the Netherworld, home of all nightmares.',
  'Пока руны не собраны вместе,': 'Until the runes are brought together,',
  'тьма лишь затаилась.': 'the darkness is only lying in wait.',
  'Эпизод 2 пройден. Впереди — Эпизод 3.': 'Episode 2 complete. Next: Episode 3.',
  'Вестник Бездны рассыпается пеплом,': 'The Herald of the Abyss crumbles to ash,',
  'и эхо его крика ещё долго гуляет по сводам.': 'his scream echoing long beneath the vaults.',
  'Трон Бездны пуст. Кристаллы погасли.': 'The Abyss Throne is empty, its crystals dark.',
  'Третья руна холодна, как дно колодца,': 'The third rune is cold as a deep well,',
  'но в ней бьётся тот же древний пульс.': 'yet the same ancient pulse beats within.',
  'Три руны из четырёх. Где-то за последним': 'Three runes of four. Somewhere beyond',
  'слипгейтом ждёт тот, кто их выковал.': 'the last slipgate waits their maker.',
  'Эпизод 3 пройден. Впереди — Эпизод 4.': 'Episode 3 complete. Next: Episode 4.',
  'Древний распадается на осколки звёзд,': 'The Elder breaks apart into shards of stars,',
  'и Кузня Рун затихает впервые за вечность.': 'and the Rune Forge falls silent at last.',
  'Четвёртая руна ложится в ладонь рядом': 'The fourth rune settles in your palm',
  'с тремя другими — и все четыре вспыхивают': 'beside the other three — and all four flare',
  'одним холодным белым светом.': 'with a single cold white light.',
  'Слипгейты гаснут один за другим.': 'The slipgates go dark one by one.',
  'Больше никто не придёт из-за них.': 'Nothing will come through them again.',
  'Вы возвращаетесь домой — последним.': 'You return home — the last one through.',
  'Сага SLIPGATE завершена. Спасибо за игру!': 'The SLIPGATE saga is over. Thanks for playing!',

  // --- сообщения по ходу игры ---
  'Секретный уровень!': 'Secret level!',
  'У входа тайник: оружие, которое вы пропустили раньше': 'A stash at the entrance: weapons you missed earlier',
  'Щит Вестника пал!': 'The Herald’s shield is down!',
  'Арена пробудилась!': 'The arena awakens!',
  'Арена побеждена!': 'Arena conquered!',
  'Слипгейт открыт — он отмечен стрелкой': 'The slipgate is open — follow the arrow',
  'Руна зажжена': 'Rune lit',
  'Древний призывает стражу!': 'The Elder summons his guard!',
  'Барьер Древнего пал!': 'The Elder’s barrier is down!',
  'Теперь его можно ранить — стреляйте!': 'Now he can be hurt — open fire!',
  'Телепорт пробуждён!': 'The teleporter awakens!',
  'Войдите в него — прямо в её чрево': 'Step in — straight into her womb',
  'Кровь отродий питает телепорт': 'Spawn blood feeds the teleporter',
  'Лава поднимается!': 'The lava is rising!',
  'На уступы!': 'Get to the ledges!',
  'Путь к руне открыт —': 'The way to the rune is open —',
  'слипгейт отмечен стрелкой': 'the slipgate is marked with an arrow',
  'Электроды молчат...': 'The electrodes are silent...',
  'Контрольная точка': 'Checkpoint',
  'Сложность': 'Difficulty',
  'Коснитесь, чтобы продолжить': 'Tap to continue',
  'Нажмите огонь, чтобы продолжить': 'Press fire to continue',
  'Нажмите огонь': 'Press fire',
  'Поверните устройство горизонтально': 'Turn your device sideways',
  'ТЕЛЕПОРТ': 'TELEPORT',
  'ВЫХОД': 'EXIT',
  'Время': 'Time',
  'Убито': 'Kills',
  'Секреты': 'Secrets',
  'Найден секретный выход!': 'Secret exit found!',
  'Мигают ключи, цветной рамкой — запертые двери': 'Keys blink, locked doors have a colored frame',
  'Кнопка «карта» — закрыть': 'Map button — close',
  'Back — закрыть карту': 'Back — close the map',

  // --- предметы ---
  'Вы получили двустволку': 'You got the Super Shotgun',
  'Вы получили гвоздомёт': 'You got the Nailgun',
  'Вы получили супергвоздомёт': 'You got the Super Nailgun',
  'Вы получили гранатомёт': 'You got the Grenade Launcher',
  'Вы получили ракетницу': 'You got the Rocket Launcher',
  'Вы получили громовержец': 'You got the Thunderbolt',
  'Вы получили лазерную пушку': 'You got the Laser Cannon',
  'Вы получили зелёную броню': 'You got the Green Armor',
  'Вы получили жёлтую броню': 'You got the Yellow Armor',
  'Вы получили красную броню': 'You got the Red Armor',
  'Четверной урон!': 'Quad Damage!',
  'Пентаграмма защиты!': 'Pentagram of Protection!',
  'Кольцо теней!': 'Ring of Shadows!',
  'Биокостюм!': 'Biosuit!',
  'Рюкзак': 'Backpack',
  'Мегаздоровье!': 'Megahealth!',
  'Вы получили серебряный ключ': 'You got the silver key',
  'Вы получили золотой ключ': 'You got the gold key',
  'Четверной урон заканчивается...': 'Quad Damage is wearing off...',
  'Защита пентаграммы слабеет...': 'Pentagram protection is fading...',
  'Кольцо теней тускнеет...': 'The Ring of Shadows is fading...',
  'Воздух в биокостюме на исходе...': 'Biosuit air is running out...',
  'У вас нет этого оружия': 'You don’t have that weapon',
  'Нет боеприпасов': 'No ammo',

  // --- двери, лифты, тайники ---
  'Лифт вызван': 'Lift called',
  'Серебряный ключ открыл дверь': 'The silver key opened the door',
  'Золотой ключ открыл дверь': 'The gold key opened the door',
  'Он отмечен на карте': 'It’s marked on the map',
  'Нужен серебряный ключ': 'You need the silver key',
  'Нужен золотой ключ': 'You need the gold key',
  'Где-то открылся проход...': 'A passage opened somewhere...',
  'Вы нашли секретное место!': 'You found a secret area!',

  // --- боссы: подсказки ---
  'Шуб-Ниггурат разорвана изнутри!': 'Shub-Niggurath is torn apart from within!',
  'Её плоть не берёт оружие!': 'Weapons can’t harm her flesh!',
  'Её плоть не берёт оружие.': 'Weapons can’t harm her flesh.',
  'Кровь её отродий пробудит телепорт': 'Her spawn’s blood will wake the teleporter',
  'Оружие бессильно против Хтона!': 'Weapons are useless against Chthon!',
  'Зарядите электроды пультами': 'Charge the electrodes at the consoles',
  'Хтон пробуждается!': 'Chthon awakens!',
  'Оружие его не берёт!': 'Weapons can’t hurt him!',
  'Зарядите оба электрода пультами': 'Charge both electrodes at the consoles',
  'по разные стороны озера': 'on opposite sides of the lake',
  'Хтон повержен!': 'Chthon is defeated!',
  'Хтон ранен!': 'Chthon is wounded!',
  'Он поднимает лаву — держитесь уступов': 'He raises the lava — stay on the ledges',
  'Хтон в ярости!': 'Chthon is enraged!',
  'Ещё один разряд!': 'One more discharge!',
  'Электрод заряжен!': 'Electrode charged!',
  'Теперь второй — на той стороне озера': 'Now the other one — across the lake',
  'Заряд электрода рассеялся — зарядите снова': 'The electrode lost its charge — charge it again',
  'Шуб-Ниггурат пробудилась!': 'Shub-Niggurath awakens!',
  'Мать чует угрозу —': 'The Mother senses danger —',
  'из-под земли рвутся щупальца!': 'tentacles burst from the ground!',
  'Вестник Бездны явился!': 'The Herald of the Abyss has come!',
  'Щит Вестника питают кристаллы!': 'Crystals power the Herald’s shield!',
  'Разбейте их.': 'Smash them.',
  'Вестник призывает грозу Бездны!': 'The Herald calls down the Abyss storm!',
  'Вестник Бездны повержен!': 'The Herald of the Abyss is defeated!',
  'Щит Вестника питают кристаллы —': 'Crystals power the Herald’s shield —',
  'разбейте их!': 'smash them!',
  'Древний пробудился!': 'The Elder has awakened!',
  'Барьер Древнего питают руны!': 'Runes power the Elder’s barrier!',
  'Зажгите все алтари.': 'Light all the altars.',
  'Древний вытягивает силу рун!': 'The Elder drains the runes’ power!',
  'Зажгите алтари снова': 'Light the altars again',
  'Древний в ярости!': 'The Elder is enraged!',
  'Древний повержен!': 'The Elder is defeated!',

  // --- эпизоды и уровни (js/levels.js) ---
  'Измерение Доблести': 'Dimension of Valor',
  'Царство Чёрной Магии': 'Realm of Black Magic',
  'Нижний мир': 'The Netherworld',
  'Измерение Древних': 'Dimension of the Elders',
  'Вступление': 'Introduction',
  'Лёгкий — прямо, в конце зала.': 'Easy — straight ahead, end of the hall.',
  'Нормальный и сложный — выше:': 'Normal and Hard — up above:',
  'лестница во дворе позади вас': 'stairs in the yard behind you',
  'ЛЁГКИЙ': 'EASY',
  'НОРМАЛЬНЫЙ': 'NORMAL',
  'СЛОЖНЫЙ': 'HARD',
  'КОШМАР': 'NIGHTMARE',
  'ВЫШЕ — СЛОЖНЕЕ': 'HIGHER — HARDER',
  'Шлюзовой комплекс': 'Slipgate Complex',
  'Замок проклятых': 'Castle of the Damned',
  'Мёртвые встают!': 'The dead rise!',
  'Некрополь': 'The Necropolis',
  'Жуткий грот': 'Grisly Grotto',
  'Древний мир': 'The Ancient World',
  'Засада!': 'Ambush!',
  'Дом Хтона': 'House of Chthon',
  'Застава у Врат': 'Outpost at the Gates',
  'Затонувший храм': 'Sunken Temple',
  'Кузни Тени': 'Forges of Shadow',
  'Лабиринт Костей': 'Labyrinth of Bones',
  'Шпиль Колдуна': 'Sorcerer’s Spire',
  'Чрево Матери': 'Mother’s Womb',
  'Врата Преисподней': 'Gates of the Underworld',
  'Кровавые Шахты': 'Blood Mines',
  'Цитадель Пепла': 'Citadel of Ash',
  'Бездонные Колодцы': 'Bottomless Wells',
  'Храм Вестника': 'Temple of the Herald',
  'Трон Бездны': 'Throne of the Abyss',
  'Мост через Пустоту': 'Bridge over the Void',
  'Обсерватория': 'The Observatory',
  'Кристальные Копи': 'Crystal Quarries',
  'Цитадель Стражей': 'Citadel of Guardians',
  'Лестница в Небо': 'Stairway to the Sky',
  'Кузня Рун': 'The Rune Forge',
  'Головокружение': 'Vertigo',
  'Здесь вдвое легче: прыжки выше и дальше': 'Half gravity here: jumps go higher and farther',
  'Зал палачей': 'Hall of Executioners',
  'Только топор! Ищите четверной урон': 'Axe only! Find the Quad Damage',
  'Арена Нижнего мира': 'Netherworld Arena',
  'Арена Нижнего мира пробудилась!': 'The Netherworld Arena awakens!',
  'Переживите пять волн': 'Survive five waves',
  'Стража цитадели': 'The citadel guard',
  'Рыцари и огр': 'Knights and an ogre',
  'Жала и крылья': 'Stingers and wings',
  'Рыцари смерти и ворог': 'Death knights and a vore',
  'Шамблер!': 'Shambler!',
  'Пять волн — выход откроется после последней': 'Five waves — the exit opens after the last',
  'Тёмная сторона': 'The Dark Side',
  'Здесь почти нет света — у вас фонарь': 'Almost no light here — you have a flashlight',
};

// Строки, где числа и имена стоят внутри фразы. t — перевод части строки.
const EN_PATTERNS = [
  [/^Волна (\d+) отбита!$/, (m) => `Wave ${m[1]} repelled!`],
  [/^Волна (\d+) из (\d+)$/, (m) => `Wave ${m[1]} of ${m[2]}`],
  [/^Кристалл разбит! Осталось: (\d+)$/, (m) => `Crystal shattered! ${m[1]} left`],
  [/^Вы получили (\d+) ед\. здоровья$/, (m) => `You got ${m[1]} health`],
  [/^Вы получили (.+)$/, (m, t) => 'You got ' + t(m[1])],
  [/^Нажмите новую клавишу для «(.+)» \(Esc — отмена\)$/, (m, t) => `Press a new key for “${t(m[1])}” (Esc to cancel)`],
  [/^Клавиша (.+) занята: пауза и выбор оружия$/, (m, t) => `Key ${t(m[1])} is reserved: pause and weapon select`],
  [/^Он отмечен на карте \((.+)\)$/, (m, t) => `It’s marked on the map (${t(m[1])})`],
  [/^(.+) — карта \((.+) — закрепить\)$/, (m, t) => `${t(m[1])} — map (${t(m[2])} — pin)`],
  [/^(.+)  рекорд!$/, (m, t) => `${t(m[1])}  record!`],
  [/^(.+)  \(рекорд (.+)\)$/, (m, t) => `${t(m[1])}  (record ${t(m[2])})`],
];
